name: code_gen
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: shallow <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mustache4dart: any
  analyzer: any

dev_dependencies:
  test: ^1.0.0
