name: renderable
description: An element-model-based Dart code generator. CodeGen's AnalyzerConverter can convert SourceGen code to CodeGen code by calling one method.
version: 0.1.10
homepage: https://github.com/copydog/renderable.dart
author: copydog <188166004@qq.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  mustache4dart: any
  analyzer: any

dev_dependencies:
  test: ^1.0.0
