name: renderable
description: >
  An element-based Dart code generator. AnalyzerConverter can create Renderable code from builder by calling one method.
version: 0.4.0+1
homepage: https://github.com/copydog/renderable.dart
author: copydog <188166004@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  analyzer: any
  meta: ^1.1.8

dev_dependencies:
  test: ^1.0.0
