builders:
  shared_renderer_builder:
    import: 'package:demo/builder.dart'
    builder_factories: ['mirrorBuilder']
    build_extensions: { '.dart': ['.mirror.dart'] }
    auto_apply: root_package
    build_to: source

  demo|builder:
    import: 'package:demo/builder.dart'
    builder_factories: ['demoBuilder']
    build_extensions: { '.dart': ['.demo.dart'] }
    auto_apply: root_package
    build_to: source
