name: demo
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: shallow <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  renderable:
    path: ../../code_gen
  analyzer: any
  build: any
  source_gen: '>=0.8.0'
  build_config: '>=0.3.0'
  rxdart: any
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  build_runner: any
