name: demo
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  renderable:
    path: ../../renderable.dart
  analyzer: any
  build: any
  source_gen: '>=0.8.0'
  build_config: '>=0.3.0'
  rxdart: any
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  build_runner: any
